Q. Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

In [1]:
import numpy as np
x = np.array([1,2,3,4])
N = 4
np.vander(x,N, increasing = True)
np.column_stack([x**(N-i-1) for i in range(N)])

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]], dtype=int32)

Q. Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [3]:
x = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
x

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [6]:
def moving_average(array,window):
    return np.convolve(array,np.ones(window),'valid')/window

moving_average(x,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])